version: "3.8"

services:
  api:
    container_name: foo-api
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    build:
      context: .
      dockerfile: docker/Dockerfile.server

    ports:
      - "8000:8000"
    environment: #переменные среды, например URL для подключения к БД
      - WATCHFILES_FORCE_POLLING=true
    volumes: #Монтируем локальную папку в контейнер, чтобы при разработке изменения были видны сразу
      - ./app:/app/app
    restart: on-failure

  #   depends_on:
  #     - rabbitmq

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   hostname: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
