version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: foo-api
    # evironment: #переменные среды, например URL для подключения к БД
    volumes: #Монтируем локальную папку в контейнер, чтобы при разработке изменения были видны сразу
      - .:/app
    #depends_on: #Зависимость от других контейнеров, гарантирует что будет запущен после запуска других контейнеров
